### ISSUE TITLE
Use SSL by default

### ISSUE THREAD

**Issue by vatima2016** [akamai-open/NetStorageKit-Java#10]
CMS example is using constructor setting useSSL to false.
Default value should be always true, to prevent stealing of user name and password during insecure communication.

```
Now: public NetStorage(String hostname, String username, String key) {
        this(hostname, username, key, false);
    }
```

Should be:
```
public NetStorage(String hostname, String username, String key) {
        this(hostname, username, key, true);
    }
```

**Comment by colinbendell** [comment]
I've removed the unencrypted option all together. It now requires TLS all the time. There should not be a use-case for unencrypted communication to netstorage.

**Comment by colinbendell** [comment]
Resolved in v.3.6
