### ISSUE TITLE
Use Standard Maven Versioning...

### ISSUE THREAD

**Issue by jwcarman** [akamai-open/NetStorageKit-Java#12]
Typically, Maven projects do not have a non-SNAPSHOT version in their pom.xml file.  When you cut a release, you remove the "-SNAPSHOT" and create a tag for that release.  Using the maven-release-plugin makes this very simple:

https://maven.apache.org/maven-release/maven-release-plugin/

Also, uploading this jar file to Maven Central would make using this API so much easier (there's another issue open for this already).  Right now, we have to build and deploy this to our own Nexus server.

**Comment by colinbendell** [comment]
This was left over from an internal release. fixing.
