### ISSUE TITLE
Use Proper Encapsulation

### ISSUE THREAD

**Issue by jwcarman** [akamai-open/NetStorageKit-Java#13]
In the NetStorage class, you have:

```
public String hostName;
public String username;
public String key;
public Boolean useSSL;
```

This, along with the fact that there is no interface, provides a nightmare for when you want to share this thing in your application with other folks.  These fields can be modified by anyone.

**Comment by colinbendell** [comment]
moved to using a credential bean

**Comment by colinbendell** [comment]
This is now inline with the edge-grid signers who utilize com.akamai.auth.ClientCredential interface. The netstorage specific interface (com.akamai.auth.DefaultCredential) has specific requirements that differ from the edge-grid auth model so it does require the Netstorage class to be aware of the differences when calling the Signer. This is unfortunate but I'll clean that up at some future time.
