### ISSUE TITLE
Make NetStorage artifact accessible with global maven repository

### ISSUE THREAD

**Issue by dborisenko** [akamai-open/NetStorageKit-Java#9]
Could you please publish NetStorage to the global maven repository? It would be nice to have it there, but not work with it locally.

**Comment by kieste** [comment]
+1

**Comment by rnrneverdies** [comment]
+1

**Comment by colinbendell** [comment]
I will be releasing v3.6 to the central repository shortly. stay tuned.

**Comment by colinbendell** [comment]
v3.6.6 is being propagated to the central repository now. You can find the staging release here:
https://oss.sonatype.org/content/groups/staging/com/akamai/NetStorageKit/3.6.6/

```xml
    <groupId>com.akamai</groupId>
    <version>3.6.6</version>
    <artifactId>NetStorageKit</artifactId>
```
